media:
  input: assets
  output: /assets

content:
  - name: artists
    label: Artistit
    type: file
    path: Data/artists.json
    format: json
    list: true
    fields:
      - name: name
        label: Nimi
        type: string
        required: true
      - name: studio
        label: Studio / kaupunki
        type: string
      - name: instagram
        label: Instagram
        type: string
      - name: image
        label: Kuva
        type: image